fix: SC2164 (warning): Use 'cd ... || exit' or 'cd ... || return' in case cd fails

diff --git a/control b/control
--- a/control
+++ b/control
@@ -238,7 +238,7 @@ function local_check {
       echo -e '\033[1m[BAD]\033[0m Git not initialized!'
     fi
 
-    cd "$OLDPWD"
+    cd "$OLDPWD" || { echo "Faile to change directory $OLDPWD"; exit 1; }
     echo
   done
 
